# Generated by Django 5.1.3 on 2024-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorvisit',
            name='visit_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoryvisit',
            name='visit_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genrevisit',
            name='visit_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
