# Generated by Django 5.1.3 on 2024-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_authorvisit_visit_count_categoryvisit_visit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvisit',
            name='visit_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
