# Generated by Django 5.1.3 on 2024-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookvisit_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='\\uploads\\users\\images\\default.png', null=True, upload_to=''),
        ),
    ]
