# Generated by Django 5.1.3 on 2024-11-20 23:07

import books.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default=books.models.get_default_author_image, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default=books.models.get_default_book_cover, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='authorvisit',
            unique_together={('user', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='bookvisit',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryvisit',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='genrevisit',
            unique_together={('user', 'genre')},
        ),
    ]
